#include <iostream>
#include <string>
#include <cstdlib>
#include <unistd.h> // Para sleep()

using namespace std;

int main() {
	int opcion = 0;
	bool continuar = true;

	system("clear");

	// TITULO
	std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"XXXXNNNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"l,lodddddooodddooollloolllooxxxxxxkkOOOOO00KXNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"XdcOWMMMWWNNNNNXKK0OOOOOkkkxxxxxdoooddddooooxxxdddddddoooooodddooooodddddxxkkkkOOO00KKKKKXXXNXNNWWWMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MWOloKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXXKK00000OOOOOOOkkxkkxddddooooddooooooooddddddddxxxxddddooddxxKMM" << std::endl;
	std::cout <<"MMMNxcxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNXK00Okkxxddoolllcc::;;;;,;;;::kWM" << std::endl;
	std::cout <<"MMMMMKol0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXXK0000OkxxxxxdooooooodddodxxddooodooooddddxkkOOOOOOxxxkkxxodKMM" << std::endl;
	std::cout <<"MMMMMMWkldXMMMMMMMMWWNNXXXKK0000OkkkkxdddooooooddoddxdddxdddddxxddddxxxkkOOO0KKXXXWMMMMMMWWNXKK0Okxdlc::;,'...    .;xXMM" << std::endl;
	std::cout <<"MMMMMMMMNxlododxxddddddoooooooooddddxkkOOO00KKKXXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkl;'.....               .;dKWMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMXOOO000OkkkkkxxdoookXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNX0kdl:,'.             ,o0WMMMMMMM" << std::endl;
	std::cout <<"MMN0xxdoolc::;''...           'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXOxolloc.   .xNMMMMMMMMMM" << std::endl;
	std::cout <<"MMNOl,.                        lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kKMMK,   ;XMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMW0d:.                     ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKO0NMMXdcxNk. lWMX;   ,KMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMWXkl,.                 cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMXxldXWd. .kMMk. ,Kk. lWMNc   '0MMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMWKx;              .xMMMMMMMMMMMMMMMMMMMMMMMMWNWWWX0kkXMMMMM0:'cKMWo  lN0'   oWMk. ,KO. cWMWc   '0MMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMMMO.            .lNMMMMMMMMMMMMMMMMMWNKOxl;,dWX0c. '0MMMMNl  .OM0' .OX:    ;KMk. ,K0' :NMWc   .OMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMMMx.           .oNMMMMMMMMMMWXXWMMM0c'.    .kMk:.  oWMMMM0'  .kWl  :Xd  .. .xMk. '00, :NMMo   .xMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMMN:          'cOWMMMMMMMWOo:,'oNMMWl    .':xNNc   .kMMMMWd    ok. .d0'  ol  cNk. .k0, :NMMo    dMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMMO'      .;okOOXMMWWMMMWd.  .lXMMMK,   ;0NMMMO.   :XMMMMX: .. ';  ;0c  .;,  '0O.  .'  :XMMo  .,OMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMMd     ;d0WKc..oxl;;o0Xd.  .dNMMMMO.   :kdo0Wo    dMMMMMk. cl     ox.       .dk.    .'dNMM0dkKNMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMWc    :XMMWd. ;xc.   ..   .kWMMMMMx.      '0X;   '0WKOKNc .OO.   'd,  .cdd,..xKlcokOKNMMMMMMMMWNNWMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMK,   .xMMMX; .xMWKo'     .kMMMMMMN:   .:lo0Wx.   .:,..o0' ;XX: ..od;:cOWMWXKXWMMMMWNX0Okxddol:,':0MMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMMx.   ,KMMMk. ,KMMMNl      'lOWMMMK,   ,dlcON:      ..:00c:OMWKk0XWWWMMWWX0Okxxoodxxxdoc,'',:ccox0NMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMN:    lWMMWo  oWMMNo.  ,;.   .,o0Wk.   ..':0Xl;looxk0NWMWMWWNKKOOkxdooddxxddddkxxdddooddddk0NWMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMO'   .OMMMK, .OMMNo. .oNWKx:;:ld0W0loxO0XNWMMWWNXK0OkxxxdddddooddkkO0KXNWWXOxddooodk0KNMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMMx.   cNMMWd. :NMNo..'dNMMMMMMMMMMMWNK00OkxxddoddoooodxkOKKNWWMMMMMMNKOxdoooodk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMWl   .xMMMNd:oKMMKxkKNWWNXKOkxddodxxxdoddxkO0KXNWMMMMMMMMMMMMWX0kdoddooxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMXl,:okNMMMWNXK0OkxddoodddxxxxkkOOKXWMMMMMMMMMMMMMMMMMMWNKOxoodddxkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMN0OOOkxdooooooddxkO0KXNWWMMMMMMMMMMMMMMMMMMMMMMWXX0OxoolooxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMMOcldxkOO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOxdddooodk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMNooWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0kdoddoodkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMMOcOMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kolooddxOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMWdoNMMMMMMMMMMMMMMMMMMMWNKOxdoodddk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMM0lkMMMMMMMMMMMMMMWXOxddddooxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMMxcXMMMMMMMMNKOdooddodk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMNoxWMWN0kdoodoodkKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMMO:odooooxkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	std::cout <<"MMMMMMMM0::dOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << std::endl;
	while (continuar) {
		cout << "\n=========== MENU PRINCIPAL ===========\n";
		cout << "1. Jugar\n";
		cout << "2. Instrucciones\n";
		cout << "3. Creditos\n";
		cout << "4. Salir\n";
		cout << "======================================\n";

		cout << "Selecciona una opcion: ";
		cin >> opcion;

		switch (opcion) {
		case 1: {
			int vidas = 3;
			int nivel = 1;
			float progreso = 0.0;
			int puntos = 0;
			bool jugando = true;

			string preguntas[3][10] = {
				{	// Nivel 1 - Informatica
					"Que es un compilador?",
					"Que hace la RAM en una computadora?",
					"Que sistema operativo es de codigo abierto?",
					"Que lenguaje se usa para desarrollo web?",
					"Que significa HTML?",
					"Que componente ejecuta las instrucciones en el PC?",
					"Que extension tiene un archivo ejecutable en Windows?",
					"Que significa CPU?",
					"Que es un bit?",
					"Que herramienta permite editar texto plano en Linux?"
				},
				{	// Nivel 2 - Videojuegos
					"Quien es el personaje principal de Mario Bros?",
					"En que consola aparecio por primera vez Sonic?",
					"Que genero es FIFA?",
					"Que estudio desarrollo The Witcher?",
					"Que personaje es de League of Legends?",
					"Que consola es de Sony?",
					"Que juego usa una Trifuerza?",
					"Que significa MMORPG?",
					"Que boton se usa generalmente para saltar?",
					"Que juego popular tiene un modo Battle Royale?"
				},
				{	// Nivel 3 - Combinado
					"Que lenguaje se usa en motores como Unity?",
					"Que tipo de memoria usan las tarjetas graficas?",
					"Que empresa creo el sistema operativo Windows?",
					"Que tipo de entrada usan la mayoria de gamepads?",
					"Que motor grafico usa Unreal Engine?",
					"Que es una GPU en videojuegos?",
					"Que significa FPS?",
					"Que se necesita para jugar en linea?",
					"Que tipo de archivo usa un videojuego para sus texturas?",
					"Que es un bug en un videojuego?"
				}
			};

			string opciones[3][10][4] = {
				{
					{"1. Ejecuta codigo linea por linea", "2. Convierte codigo a lenguaje maquina", "3. Analiza redes", "4. Optimiza graficos"},
					{"1. Procesa imagenes", "2. Almacena informacion temporal", "3. Controla energia", "4. Mejora sonido"},
					{"1. Windows", "2. MacOS", "3. Linux", "4. DOS"},
					{"1. C++", "2. Python", "3. HTML", "4. Pascal"},
					{"1. Lenguaje de maquinas", "2. Lenguaje de marcas de hipertexto", "3. Hoja de calculo", "4. Red de computadoras"},
					{"1. Disco duro", "2. Memoria RAM", "3. CPU", "4. Placa madre"},
					{"1. .txt", "2. .exe", "3. .html", "4. .doc"},
					{"1. Central Processing Unit", "2. Control Panel Utility", "3. Compute Power Unit", "4. Central Peripheral Unit"},
					{"1. Unidad de almacenamiento", "2. Unidad de tiempo", "3. Dato binario", "4. Unidad de imagen"},
					{"1. Word", "2. Gedit", "3. Excel", "4. Chrome"}
				},
				{
					{"1. Luigi", "2. Mario", "3. Bowser", "4. Toad"},
					{"1. PlayStation", "2. Nintendo", "3. Sega Genesis", "4. Xbox"},
					{"1. Aventura", "2. Deporte", "3. Puzzle", "4. Terror"},
					{"1. EA", "2. Rockstar", "3. CD Projekt Red", "4. Ubisoft"},
					{"1. Ezio", "2. Ahri", "3. Kratos", "4. Master Chief"},
					{"1. Xbox", "2. PlayStation", "3. Nintendo", "4. Atari"},
					{"1. God of War", "2. Final Fantasy", "3. Zelda", "4. Mario"},
					{"1. Massive Multiplayer Online Role Playing Game", "2. Movimiento rapido", "3. Jefe final", "4. Rol offline"},
					{"1. X", "2. B", "3. A", "4. Y"},
					{"1. Fortnite", "2. Minecraft", "3. FIFA", "4. GTA"}
				},
				{
					{"1. HTML", "2. JavaScript", "3. C#", "4. Python"},
					{"1. ROM", "2. VRAM", "3. DRAM", "4. BIOS"},
					{"1. Google", "2. IBM", "3. Microsoft", "4. Apple"},
					{"1. HDMI", "2. VGA", "3. USB", "4. Inalambrica"},
					{"1. Unity", "2. Lumen", "3. Nanite", "4. Unreal Engine"},
					{"1. Unidad de disco", "2. Tarjeta grafica", "3. Procesador", "4. Disco duro"},
					{"1. Fotogramas por segundo", "2. Fase previa de sonido", "3. Free Play Style", "4. Fast Press Shot"},
					{"1. Telefono", "2. Conexion a Internet", "3. Cable USB", "4. Mando"},
					{"1. .docx", "2. .png", "3. .exe", "4. .zip"},
					{"1. Error del juego", "2. Mejora grafica", "3. Modificacion legal", "4. Modo extra"}
				}
			};

			int respuestas[3][10] = {
				{1, 1, 2, 2, 1, 2, 1, 0, 2, 1},
				{1, 2, 1, 2, 1, 1, 2, 0, 2, 0},
				{2, 1, 2, 2, 2, 1, 0, 1, 1, 0}
			};

			for (nivel = 0; nivel < 3 && jugando; nivel++) {
				system("clear");
				cout << "\n========== NIVEL " << nivel + 1 << " ==========";
				if (nivel == 0) cout << " (Informatica)\n";
				else if (nivel == 1) cout << " (Videojuegos)\n";
				else cout << " (Combinado)\n";

				for (int i = 0; i < 10 && vidas > 0; i++) {
					if (nivel == 0) {
						std::cout <<"MMMMMMMXd;.                                                                                                  .;dXMMMMMMM"<< std::endl;
						std::cout <<"MMMMMX:  'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'  :XMMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMWO;.                                                                                      .;OWMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMWX:  .cllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc.  :XWMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK;  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:  ;KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ;KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ;XMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxdOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ;XMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx''oNMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMMMMN00NMMMMMWO;   ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMMNk;..oWMMMKl.  'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMWMMMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMW0:.  ,OWMNx'  .oXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:;kWMMNc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMKl.  'xXWWk,  .:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ;XMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMWo  .lXWWKc.  ,kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMWXxx0WMXd.  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMWMNk,  .cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMW0:.  ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMXo.  'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMWk'  .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMWd..:0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMWXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMK,  :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:  ,KMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  :XNN0,  ;KNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNK;  ,0NNX:  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  ..''.    ....................................................................................    .''..  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  ..''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''..  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  :XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX:  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOoccccccccoOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMM0'  cWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl          lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWc  '0MMMMM"<< std::endl;
						std::cout <<"MMMMMK,  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOkkkkkkkkONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  ,KMMMMM"<< std::endl;
						std::cout <<"MMMMMWx.  ,okkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkko,  .xWMMMMM"<< std::endl;
						std::cout <<"MMMMMMWO;.                                                                                                    .;OWMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMN0xoccccccccccccccccccccccccccccccccccc'   ,cccccccccccccccc,   'cccccccccccccccccccccccccccccccccccox0NMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl  .OWMMMMMMMMMMMMMMWO.  lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc  '0MMMMMMMMMMMMMMMM0'  cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;  ;KMMMMMMMMMMMMMMMMK;  ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,  :NMMMMMMMMMMMMMMMMN:  ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  oMMMMMMMMMMMMMMMMMMo  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMNK0000000:  .l000000000000000000l.  :0000000KNMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.   ...      ..              ..      ...   .cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc::::::::::::::::::::::::::::::::::::::::::ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMN0doooooooooooood0WMMMXxoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooood0NMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMKc.               cXMMWo                                                               .cKMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMNl  .cddddddddddddxKWMMMXkddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddc.  lNMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMWk.  cNWMMMMMMMMWWWWWWMMMMWWWWMMMMMWWWWWMMMMMWWWWWMMMMMWWWWMMMMMWWWWWMMMMWWWWWMMWMMMMMWNc  .kWMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMX;  '0MMMMMMMMNd;,,;dNMM0c,,,c0WMNx;,,;dNMMKc,,,':OMMWk;,,,oXMMKl,,';kWMNx;,,;dNMMMMMMMM0'  ;XMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMWo. .dWMMMMMMMMXl....oXMMO,...,OMMNo....lXMM0;....'kMMNd....cKMM0:...'xWMNo....lXMMMMMMMMWd. .dWMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMO'  :XMMMMMMMMMMWXXXXWMMMMNXXXNMMMMWXXKXWMMMMNXXXXNMMMMWXXXXWMMMMNXXXNWMMMWXXXXWMMMMMMMMMMX:  'OMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMNc  .OMMMMMMMMMMNkc::ckNMMKo:::oKMMWkc::ckNMMXo::::l0WMWOc::cxNMMXd:::l0WMNkc::ckNMMMMMMMMMMO.  cNMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMWx.  oWMMMMMMMMMWXc.  .lXMMk'   .kMMNl.  .cKWMO'    .xWMNo.  .:KMM0;.  .dWMXl.  .cXWMMMMMMMMMWo  .xWMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMM0,  ;KMMMMMMMMMMMWN0OO0NMMMWK0O0KWMMMN0OO0NWMMWXOOOOKWMMMN0OOOXMMMWX0OOKNMMMN0OO0NWMMMMMMMMMMMK;  ,0MMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMWl  .oKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKo.  lWMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMWd.  ............................................................................................  .dWMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMXo.                                                                                              .oXMMMMMMMMMM"<< std::endl;

					} else if (nivel == 1) {
						std::cout <<" MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd...................:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:.  .,.               ,:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'   .kNd.                :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'    .'.                 ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'                        :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'                        :XMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'            .',,,,,,,,,,dNMMMMMMMMMMMW0kkKWMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'            :XNNNNNNWWWWWMMMMMMMMMMMKl.  .dNMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'            .,,,,,,oXMMMMMMMMMMMMMMMk.    ;XMMMMWMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMWOlxNMMMMMMMMMMMMMMMMMMOl;.        .'ckkxkkkkk0WMMMMMMMMMMMMMMMk.    ;XMNdcONMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMWo ,KMMMMMMMMMMMMMMXdll'           .;kMMMWMMMMMMMMMMMMMMMMMMMMMk.    ;XMx. 'OMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMo .d0XMMMMMMMMW0OOo.              .,oKKKXWMMMMMMMMMMMMMMMX0NMMk.    ;XMd  .kMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMWo   .dXNWMMMWNO,                   .';'.:KMMMMMMMMMMMMMM0,.lNMk.    ;XMd  .kMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMo    ..oNMMMx'.                   .;dXo.;KMMMMMMMMMMMMMMo  ,0Mk.    ;XMd  .kMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMWo      .;:::.                     .;kMXO0WMMMMMMMMMMMMMMo  ,KMk.    ;XMd  .kMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMWo                                 .;kMMMMMMMMMMMMMMMMMMMo  ,KMk.    ,0No  .kMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMWk:'                               .:kMMMMMMMMMMMMMMMMMMWo  ,KMk.     ... ,dXWMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMWO,.                           ,xO0XMMMMMMMMMMMMMMMMMMMo  ,KMk.    .',;dXMWWMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMWX0:                         .oWMMMMMMMMMMMMMMMMMMMMMMx. .cd:.    ,KWWWMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOo.                    .l0XMMWMMMMMMMMMMMMMMMMMMMMWKo.        ;KMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMXko'                ;dkXWMMMWMMMMMMMMMMMMMMMMMMMMMMW0xxc.    ;KMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMWMMMKxdddddddddddddddddd0WWOo,      .:l,    dMMMWKddddddddddddddddddddddddddxXMk.    ;KNOdddddddddd0WMMWMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMXOkOOOOOOOOOOOOOOOOOKWMMMx.   .,lKMk:'  dMMMWXOkkOOOOOOOOOOOOOOOOOOOOOOO0NMk.    ;KWKOOOOOOOOkOXWMWMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMNXNNNNMMMMMMMMMMMx.  .dWWWMWWK, oMMMWWMMMMMMMMMMMMMMMMM0dddKMMMMMMMk.    ;KMWNNNWMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMWOdddd0WMMMMMMMMMMx..l0XWMMMMMK, dWMMWWMMMMWMMMMMMMMMMMMX000XMMMMMMMk.    ;KMNOdkXMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMWXKXKXWMMMMMMMMMMWXKXWMMMx. ;o0MMMMMMK, ,lxXWWMNKk0MMMMMWXKKKXNWMMMMMMMMMMMk.    ;XMMMMMMWXKNMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMWXkdddONMMWMMMMMMMNOdONMMW0l::cOMMMMMMXo:::oKWWMWWNNMMMMMNkoddd0WMMMMMMMMMMMO.    ;XMMMMMMWOdKMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOkkkkKWMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMN0xooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooookKWMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMKddO0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000koxKMMWMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMo;KMMMMMMWWMMMMMMMMMMMMMMWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMWMMMMMMMMMMMWMO,dMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMo;KMMKdlookXNklkkoONNkONkoood0NNOdooON0dokXNkOWWWOkkooddxXWMMMW0xoooxKXkod0XkxNW0xkxooooxXMWMO,dMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMo;KMMk'l00lcKd'dl'lxx;:lcO0Okcokl:cdKd,;:,c0ccWWXc::.;::cxXMMMx:x0xclxc,:;,l:'ddc'c,.lxOKNMMMO,dMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMo;KMMk,xWWo;0k;ko:KKd'c:cWWMX:lWKkxldc,dk;;OclWWNc:c,do;cKMMMMd,OMXo,c;:xo,::lK0k:c;;OXWMMMMMO,dMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMWMMo;KMMO;:oooxXd'docXMNlokooooooOOooookolXMdcKOoooookolXWXkdOWMMKooooodxcxMXllloWM0coc;oodxXMMMO,dMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMWMMo;KMMWK000XWWXKXXXWMWXNMX0K0KNWX000NMNXWMNXWMN00KNWNXWWMMXXWMMMWK00KNWXNMWNNXNMMWXNX0000KWMMMO,dMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMkcxNMMWWMMMMMWMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdcOMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMKxdddoooddoodooddoooooooododooddoodoodoodoooooddoodddoodddooododddddddoddodddoddodddoodoododkXWMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMWNXXXKKXXKXXKXXKKXXXXKXXXKXXKXXXXXXXXKXXXXKXXXXKXXKKXXXXXXKXXXXXXXXXXXXKKXXXXXXXXXXXXXXKKKNMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;

					} else {

						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xolccccoxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,.          'l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx:.             .:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd;l'             .l:lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0',o.             .c,.OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;.,'             ',.;ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,.                  ,xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKKKKKKKKKKKKo...  .            ...lKKKKKKKKKKKKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,.............,;,,.;l.       .c;.',;,.............'xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd                .,::c:,'''''',:;;;'.               lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd               ';,,'.....:loddxxdl:,.              lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd            ..:c.        .....',lxoc:'..           lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd        ',,',,'.                'd00xxdo:,'        lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd      .:;.                    ..;lccd0XNKko:.      lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd     .c'          ...............    .,oKN0o;.     lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd    .c,             ..''',,,'..         'kWOl,     lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd    ::                                   :XNxc,    lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd   'c.                                    :XXd:.   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd  .c:                                     .xWxc;.  lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdlc'       ..'',,''''''''''''''''''''..    .okxdlco0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWW0,     .,,,''',,,,,,,,,,,,,,,,,,,,,'',',,.  .cOoxWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o;,ox,    .;:..;lxO0XXNNNNWWWNNNNNNNNXK0kdl;..:;. .dkodc,,;lONMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMWKd;.  'c.     ;:.;0WWN0xocccccccccccccccccox0NMW0;.;;  ,Od::.    ,o0WMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMWXx:.     lx.    .:'.OMNx,.                     .,xNMO.':. :o;:c'      .;dKWMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMWXkc.        ;d;    .c.;XWo.                         .dWX;.:. ,; .c.         .:xXWMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMNk;............::.   'c.:N0,                           '0N:.:' ...:,.            'dNMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMNd:c::c::cc:::::::cloOl cWk.                           .kWc lkolc:;;:::::::::::::;dNMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMNkccllcoXl lWx.                            dWl lXdcllllkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc;kNMNO,c: oWl                             lWo :l,kWWNk;cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc;0Nkc,'.;; dX;                             ;Xd.;;..,ckNK;cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,k0;     ;; dO.                             .kx.;;     ;0k'dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMWX;:Xl      ;;.xo                               ok.,;      cXc;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMXc;xdlloc,'l;.o;                               ;o.;l''cllldx;cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkolodc. lK;.;.                               .;.;Kl .codolkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWK, lK;                                     ,Ko ,0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN: :0;                                     'k: ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl ,x;      ..';:clooddddddddollc:,'.       .. cWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd.... .;ldk0XNMMMMMMMMMMMMMMMMMMMWNX0xoc,.    oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMx..:oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKxl,.oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
						std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
					}
					cout << "\nPregunta " << (i + 1) << ": " << preguntas[nivel][i] << "\n\n";
					for (int j = 0; j < 4; j++) {
						cout << opciones[nivel][i][j] << endl;
					}

					int respuesta;
					cout << "\nTu respuesta (1-4): ";
					cin >> respuesta;

					if (respuesta - 1 == respuestas[nivel][i]) {
						cout << "\nCorrecto!\n";
						if (nivel == 0) puntos += 10;
						else if (nivel == 1) puntos += 20;
						else puntos += 30;
					} else {
						cout << "\nIncorrecto. Pierdes una vida.\n";
						vidas--;
					}
					sleep(2);
					system("clear");
				}
			}

			if (vidas <= 0) {
				cout << "\nGAME OVER\n";
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMN0O0OOOOOOOOO0000000OKWWK00000OOOOOOO00XWNK0000OOOOOO00XNKOOO00000000000000OOOOOOOOO00000OOOKWMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMO' .              .  :KX:             .lNO, ...     ...d0,         ..                       ;KWMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMWMXo;.   'cccccccccccc:.  .,,.  .:cccccc:.  .,'    'cccc;.  .'   .cccc;.  .:cccccccccccccccccc.  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMWOdl.   .'kMWXKKKKKKKKKO;      ..oNWX0KNMK:..      .oMMMW0:..   ..dWWMMK,  :XMMMWX0KKKKKKKKKK00:  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;     :KXNMK:..........      'kKNMWo..xMWXKd.     .oMMMMWXKo. ;0KNMMWM0,  ;XMWMNl.............   ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  .od0WNx:,.             .cdONMOc:.  ':lKMXxd;   .oMMMMMMMXxdOWMMMMWM0,  ;XMMMN:              ':dXMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  :NMMMX;     .,,',,,'.  .OMMMMd       .kMMMMx.  .dMMMMMMMMMMMMMMMMMM0,  ;XMMMWd,,,,,,',,'.  .OMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  :NMMMX:    'kNNWWWNXc  'OMMMMd.      .kWMMMx.  .dMMMMMWWWMWWWNWMMMM0,  ;XMMMMNXNNNNXXXNNo  .OWWMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  :NWMMN:     .'oNWWWNc  'OMMMMXOOkkkkO0NMMMMx.  .dMMMWKc'lXMk,,xWMMM0,  :XMMMNd''''''''',.  .OWWMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  .loOWWxc;.    ;XMWMNc  'OMMMMKdooooooxXMMMMx.  .oMMMMO' .co,  lWMMM0'  ;XMMMN:              ';oXMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;     :0KNMK:....cXMMMNc  .OMMMMd       .kMMMMx.  .oMMMMO'       lWMMM0,  :XMMMNl.............   ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMW0xl.   ..xWWXKKKKXWMMMNc  .OMMMMd       .kMMMWx.  .dMWMMO'       lWMWM0,  ;XMWMWNKKXKKKKKKKKK0:  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMM0'     ':::::::::::::.   ,c:::'        ':::c'    .:::c,        .:c::;.  .;c::::::cc::c:::c::.  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMM0'                  ,dd:                     :xl,.                   .lx;                     .;KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMW0xl.  ............... cXNd.......        ......:dc,.....................cd:.................  .,:dNMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMWX:     cKXKKKKXKKXKKKc ..'..xKXKKl       .dXXKXl.  .lKKKKKKKKKKXXXXXXXXk'  ,OKKKXKKKKKKKKKXKl     ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMWX;  .od0WNx:::::::xNW0do'  .OMMMMd       .kMMMMx.  .oWWMWKo::::::::::::,.  ;XWWMNx:::::::dNMKdo'  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  :NMMMX:       ;XWMMNc  'OMMMMd       .kWMMMx.  .oWMMMO.                ;XMMMN:       ,KMMMWc  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  :NMMMX;       ;XMMMNc  .OMMMMd       .kMMMMx.  .dMMMMO'                ;XMMMN:       ;KMMMWc  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  :NMMMX;       ;XMMMN:  .OMMMWXOk,  ck0NMMWWx.  .oMMMMN0kkkkkOkkkx'     ;XMMMN:    .ok0NMMMWc  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  :NMMMX:       ;XMMMN:  .:okNMWMWkcl0MMMMXxo;   .dMMMMXxoooooooool.     ;XMMMNx:c::oKMKxoooo'  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  :NMMMX:       ;XMMMNc     'kKXWMMMMWWWXKd.     .dMMWMO'                :XMMMWXKXNMMMMk'.      ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  :NMMMX:       ;XMMMNc      ..lNMWMMWWK:..      .oMMWMO'                :XMMMNl.,OMMMMNXKc     ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMX;  .:ckWWOoooooookNWOc:.  .,,.  .:ckWNx:;.  .;'   .oMMMMXxooooooooooooc.  :XMMMN:  ,cdXMWMM0do'  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMXc     ;kkOkkOkkkkOOk;     ;KX:     ;kx'     lWO.  .:kOOOkkOkOOkkkkkkkkd.  'xkkOx'    .oOOOOkkk,  ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMWX0d.                   .d0KWWXOd.        ,k0XWO.                                                 ,KMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMXdllllllllllllllllllldXMMMMMMXxllllllllkNMMMXdlllllllllllllllllllllllllllllllllllllllllllllllllxNMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
			} else {
				cout << "\nFelicidades! Has completado el juego.\n";
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdoodKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdc:;;;coKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMWKo::,.  .,::oKWMMMWMMMMWMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOkk0NMMMMKoc:,.      .,:coKWN0kkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxloxxclKWKoc:,.          .,;oxcldxdcxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo:0WMMK::kl;,.              .o:oWMMMk:kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;xMMMMMd'lc.                '::0MMMMNllNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo:XMMMWMO';;                 ,:cXMMMMMx:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWlcNMMMMMK,;:                 ,::KMMMMMk;kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo:XMWMMMO.;;                 ':,xMMMWMO:ok0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXo;kMMMMWO';;                 .:,oNWWWMO:ll:oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKocd:lNWNXXNx::.                .::kKxldKk::,,:coKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKoc:,;::kKocdKXc:,        ......  ,:cKKxxkXk::. .,:coKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKoc:,.  ;:lOkk0NWx;l:,;,,,;;:llll:;.;:lXWMMMWx::.   .,::oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo::,.    .::kMMMMMK;'c:;:lc;;d0kxOd:::..;:oOXWx;:.     .,;coKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMWWKoc:,.       ;:oWMMMWWo.xK00Nk.cNWWWWWo......;llo:;l'       .,:coKWWMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMWKoc:,.        .c,,odkXWMk;kWMMMX;:NMWK0Nk,lkxxOXWNOl;,,,,.      .,:coKWMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMWKoc:,.        .:;.....;oodx;dKkkk0c;0Xxlooo;lxxXXxodONXOoc::,       .,:coKWMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMWKoc:,.         ,ccooloxONNKo,.codXOo,,odlkWOl,'lkNo,xl;kXKNW0c:;        .,:coKWMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMWWKoc:,.         ,;:lKWNXXWWKdOX0:,cOMWKl.ckooOK0:lXOdc:oocclolOW0c:,         .,:coKWMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMKoc:,.         .:clONOllc:xXkx0WM0:,oOXKc .,:lloll0d;dl:ONk;ld;dWNO::,          .,:coKWMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMWKdc:,.          '::kWMWd'lOl,odo0MMW0l::;,.     . .cx:':;,:oo:cdONW0Ox::'           .,:co0WMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMWx;c;.           .:;dW0loo:co:cd:.lNNxodo',dk0OOOOdodxxddool,':,dWMMMWxoo::.            .;c;xWMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMWOc:;.           .::xKk;:xk:':lc;'cKo;oKNo:kkxxxxkllXMMWKXMWXd,.oNMMMMNddo::.           .;:ckWMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMNxl:;.         ':cloKo:l:'dXo,d0XNo;c:dd,:OK0OOkxOWMMWOo0WMWK:.dWMMMMKdkd::.        .;:lxNMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMNxc:;.       ,:cloNWNW0:'cc:OWWMXdlc:llllloxOKNWMMMMWKKWMMWk.'OMMWMWO0Xo::.     .;:cxNMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMNxc:;.     ;:lxxNMMMW0kO0KKNNOdk0d:::;'   .,coolodkKWMMMWWo.lWMMMMWKxkl:;   .;:cxNMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMNxc:;.   ;:oko0MMMMMMMNOxkc.:kl,.    .cdx0KX0d,;kXWMMMMWk;:0MMMMM0,:kc:;';:cxNMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMWXxc:;..::d0oOMMMMMMNo.:c.lkcoXXx..cKMMMMMMMWKdlkXWMMMWXo,kMWNNWK, ck:locxXMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMXxc:cl;xNKNMMMMMMWOl:,ok:dNMWWkdOKMMMMMMMMWWXKXWMMMMX:'OXl,lx:  ,Olc0XWMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMWWMMMWWXxdo:kO0MMMMMMMWNo,dx;dWMWMMWNxdNMMMMMMMWMMMMWNXNW0,;KXl...  .dd:kMWMMMWWMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMWNXNWMMMWd:OccNMMMMMMMk;xx.:XMMMMMM0ocxXNMWWWMWWWNX0kkXWO;:ooolllllolcOWMMNXNWMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMXOkxxkdllkNMMocO;.xWMMMMMMKOd' :NMMMMMMNkolco0KOOOKKOxooxKNkcc:,,:oodxddONMNOllxkxxkOXMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMK::0NWWO,.lXWlcO, .dOKNWNNNo:l;'ckKWMMMMWNXKOk0OxooxdxO00koc:.  .cloKWMMWWXl.,OWWN0c:KMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMWKodXWMMXc.;0d:kl    .':xOl::.:;;dkKWMXxOWMMMWWN0dodddddo:;'  .;:cxXMMMMW0;.cXMMMXooKWMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMWWNxl0WMWNd.'xocodl:;cldoc:;. ;:lNWWWWNkcdXWWWNWXx'   ':'.  .;:cdXMMMMWWk'.dNMMW0lxNWWMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMWMWNklkNMMWO,.oOdoddddo,'loc:,;'lWWkokxoxkl:lxkoxNK;.;c'.,;:llcolkWWMMXo.,OWMMWklkWWWWMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMXdlxkkodXMMMMK:.:KWNK0xld0NNKXNk''0OckMWxcKo.cXMKcxOckWWo;KWNXXX0cdWMMK:.:KMMMMXdokkxloXMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMW0ookNWWMWX00Ox' 'kWM0ckW0c'.';'  ,cdWMWXloo.oNMWk:;dNMMd:KWOc::''kWWO' ,xO00XWMMMNOooONMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMW0ooONWXc..',,;;dXMdcXNc .lkxko. :XNkOW0:'.dWWWWocKWWMxcKWNXXKclNMNd:;,,'..cKWNOod0WMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMW0doONK:.cXWWMMMMkcOWO,'ckXWK,'0MNxOWWo..dMK0NNNWKKMklKWk:;;.:XMMMWWWXc.:KNOod0WMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMWKdoOKl.cXWMMMMNxckNN0kONMK:dWN0OOKWKo:kMk;kMMKcdMOoKWKkxkd:dMMMMMXl.lKOod0WMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMWKdoxd'cXWMMMMWO:,coooooc;co;.  .coc:co; 'oo;.,oc;loooool;xMMMWXc'dxodKWMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMWWKdol,cKWMMMMWx;lx, .;dxo';xl.'oxl:.  ,xo. .,ldddo:.  .cKMMMXc,lodKWWMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc.;KMMMMMxcKWd:kNXd'.oW0,:NMWWO' lWK;,kNXkdx0k, 'xNMMMK:.:xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd,:KMMMMxlKWNNKo'   dW0':NWNNW0,lWKoOWO' .';,..xWMMMK:,dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxkWMMMxcKMWWk'    dW0':NNd;xWKKWKd0Wo .dXXX0cxMMMWOxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxlKWOONXd'  dM0':NN: .dNWWKcoNXd:lxKWKcxMMMWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxcKNc.;kNKo,dNO':XX:  .lXN0, ;xKXXXNWKcxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;',.   .''..,. .''.    .,'    .'''',,;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.                              .;dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl'                          'lONWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx;...............',.....:xXWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXXXXXXXXXXXXXXNNXXXXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;
				std::cout <<"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"<< std::endl;

			}
			cout << "\nPuntaje final: " << puntos << "\n";
			cout << "\nVolviendo al menu principal...\n";
			sleep(3);
			break;
		}

		case 2:
			system("clear");
			cout << "\n========== INSTRUCCIONES ==========\n";
			cout << "1. Elige la opcion correcta para avanzar.\n";
			cout << "2. Tienes 3 vidas. Si las pierdes, el juego termina.\n";
			cout << "3. Al ganar o perder, volveras al menu principal.\n";
			cout << "4. Cada nivel tiene 10 preguntas.\n";
			cout << "   - Nivel 1: Informatica (10 puntos por pregunta)\n";
			cout << "   - Nivel 2: Videojuegos (20 puntos por pregunta)\n";
			cout << "   - Nivel 3: Combinado (30 puntos por pregunta)\n";
			cout << "\nPresiona ENTER para volver...\n";
			cin.ignore();
			cin.get();
			break;

		case 3:
			system("clear");
			cout << "\n========== CREDITOS ==========\n";
			cout << "Idea: Carou, Picco\n";
			cout << "Diseno: Giliberti, Kemptner\n";
			cout << "Codigo: Todos los integrantes\n";
			cout << "\nPresiona ENTER para volver...\n";
			cin.ignore();
			cin.get();
			break;

		case 4:
			continuar = false;
			cout << "\nGracias por jugar. Hasta la proxima!\n";
			break;

		default:
			cout << "\nOpcion no valida. Intenta de nuevo.\n";
			sleep(2);
			break;
		}
	}
	return 0;
}